RainBowAssociations/Models/ErrorViewModel.cs
namespace RainBowAssociations.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RainBowAssociations/Models/Student.cs
namespace RainBowAssociations.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set;}
        public string StudentEmail { get; set;}
        public int StudentAge { get; set;}
        public string Address { get; set; }
    }
}

RainBowAssociations/Models/Subject.cs
namespace RainBowAssociations.Models
{
    public class Subject
    {
        public int Subjectcode { get; set; }
        public string SubjectName { get;set; }
        public string SubjectTeacher { get; set; }
    }
}

RainBowAssociations/Models/Teacher.cs
namespace RainBowAssociations.Models
{
    public class Teacher
    {
        public int EmpId { get; set; }

        public string TeacherName { get; set; }
        public string Address { get; set; }
    }
}

RainBowAssociations/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RainBowAssociations.Models;
using System.Diagnostics;

namespace RainBowAssociations.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RainBowAssociations/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using RainBowAssociations.Models;

namespace RainBowAssociations.Controllers
{
    public class StudentsController : Controller
    {
        static List<Student> students = new List<Student>()
        {
            new Student(){StudentId = 1,StudentName="Ram",Address="Hyd",StudentAge=16,StudentEmail="ram@yahoo.com"},
            new Student(){StudentId = 2,StudentName="Sumith",Address="Hyd",StudentAge=17,StudentEmail="sumith@yahoo.com"},
            new Student(){StudentId = 3,StudentName="Lokesh",Address="Hyd",StudentAge=16,StudentEmail="lokesh@yahoo.com"},
            new Student(){StudentId = 4,StudentName="Lohith",Address="Hyd",StudentAge=15,StudentEmail="lohith@yahoo.com"},
            new Student(){StudentId = 5,StudentName="Sushma",Address="Hyd",StudentAge=16,StudentEmail="sushma@yahoo.com"},
        };
        public IActionResult Index()
        {
            return View(students);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Student());
        }
        [HttpPost]
        public IActionResult Create(Student model)
        {
            if (ModelState.IsValid)
            {
                students.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

RainBowAssociations/Controllers/SubjectsController.cs
using Microsoft.AspNetCore.Mvc;
using RainBowAssociations.Models;

namespace RainBowAssociations.Controllers
{
    public class SubjectsController : Controller
    {
        static List<Subject> subjects=new List<Subject>()
        {
            new Subject(){Subjectcode=101,SubjectName="Maths",SubjectTeacher="Lakshmi"},
             new Subject(){Subjectcode=102,SubjectName="Physics",SubjectTeacher="Lakshman"},
              new Subject(){Subjectcode=103,SubjectName="Chemistry",SubjectTeacher="Rohith"},
               new Subject(){Subjectcode=104,SubjectName="english",SubjectTeacher="Andriyana"},
        };
        public IActionResult Index()
        {
            return View(subjects);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Subject());
        }
        [HttpPost]
        public IActionResult Create(Subject model)
        {
            if (ModelState.IsValid)
            {
                subjects.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

RainBowAssociations/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;
using RainBowAssociations.Models;

namespace RainBowAssociations.Controllers
{
    public class TeachersController : Controller
    {
        static List<Teacher> teachers = new List<Teacher>()
        {
            new Teacher(){EmpId=100,TeacherName="Lakshmi",Address="Rjy"},
            new Teacher(){EmpId=101,TeacherName="Lakshman",Address="Pune"},
            new Teacher(){EmpId=102,TeacherName="Rohith",Address="Ndd"},
            new Teacher(){EmpId=103,TeacherName="Andryana",Address="North Koriea"},
        };
        public IActionResult Index()
        {
            return View(teachers);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Teacher());
        }
        [HttpPost]
        public IActionResult Create(Teacher model)
        {
            if (ModelState.IsValid)
            {
                teachers.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

RainBowAssociations/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RainBowAssociations/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RainBowAssociations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RainBowAssociations.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RainBowAssociations</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RainBowAssociations - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RainBowAssociations/Views/Students/Create.cshtml
@model RainBowAssociations.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentEmail" class="control-label"></label>
                <input asp-for="StudentEmail" class="form-control" />
                <span asp-validation-for="StudentEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentAge" class="control-label"></label>
                <input asp-for="StudentAge" class="form-control" />
                <span asp-validation-for="StudentAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RainBowAssociations/Views/Students/Index.cshtml
@model IEnumerable<RainBowAssociations.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentAge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentAge)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

RainBowAssociations/Views/Subjects/Create.cshtml
@model RainBowAssociations.Models.Subject

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Subjectcode" class="control-label"></label>
                <input asp-for="Subjectcode" class="form-control" />
                <span asp-validation-for="Subjectcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectName" class="control-label"></label>
                <input asp-for="SubjectName" class="form-control" />
                <span asp-validation-for="SubjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectTeacher" class="control-label"></label>
                <input asp-for="SubjectTeacher" class="form-control" />
                <span asp-validation-for="SubjectTeacher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RainBowAssociations/Views/Subjects/Index.cshtml
@model IEnumerable<RainBowAssociations.Models.Subject>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Subjectcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectTeacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subjectcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectTeacher)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

RainBowAssociations/Views/Teachers/Create.cshtml
@model RainBowAssociations.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <input asp-for="EmpId" class="form-control" />
                <span asp-validation-for="EmpId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeacherName" class="control-label"></label>
                <input asp-for="TeacherName" class="form-control" />
                <span asp-validation-for="TeacherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RainBowAssociations/Views/Teachers/Index.cshtml
@model IEnumerable<RainBowAssociations.Models.Teacher>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmpId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TeacherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmpId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeacherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>